### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by SnailRabbids** [funseek/godot-ios-firebase-analytics#1]
@yokochi  Hi, its me again :)
Is it possible to add some information about changes in the Privacy Policy due to use of this plugin? (in Readme?)
It could help a lot. Plugin works for me with Godot 3.4.4, but now I have to change my Privacy Policy and I dont know which kind of data collects now. As I can see on Firebase console, its device type (mobile/tablet) and device name (iPhone7, Ipad (9th gen)).

**Comment by yokochi** [comment]
@SnailRabbids Hi,
This plugin only uses Firebase, so this plugin itself does not collect any data. Please check Firebase to see what data is being collected.
