### ISSUE TITLE
ATT + Firebase Analytics

### ISSUE THREAD

**Issue by SnailRabbids** [funseek/godot-ios-firebase-analytics#2]
Hi @yokochi , as I know, if I want to use Firebase Analytics, I also need to add https://github.com/DrMoriarty/godot-ios-att. The Firebase Analytics plugin runs without any code, I mean, I don't need to create a node where I call some data collection methods, but I have to prevent data collection if the user doesn't agree. How can I disable Firebase Analytics plug-in? Or will it be turned off automatically if the user rejects the data collection in the ATT plugin?

**Comment by SnailRabbids** [comment]
@yokochi 
As I see it: I will ask the user to collect his data (using the ATT plugin), and then, if he agrees -> run the Firebase analytics plugin, otherwise -> do not run fba. But right now, fba plugin runs automatically with application start and I cannot prevent it.

**Comment by yokochi** [comment]
Hi @SnailRabbids , ATT is required to obtain IDFA, which is irrelevant since Firebase Analytics does not obtain IDFA, and ATT is required when you include an Ad module (e.g., AdMob).

**Comment by SnailRabbids** [comment]
@yokochi I found info here: https://firebase.google.com/support/privacy#data_processing_information. See "Google Analytics for Firebase" in the table (last line): "Retention: Google Analytics for Firebase stores certain data related to ad IDs (e.g. Apple's ID for advertisers and vendor ID, Android ad ID) ...". This is the only information I found. Is "Apple's ID for advertisers" and IDFA same thing?

**Comment by SnailRabbids** [comment]
@yokochi And here is info from Apple: _"The app privacy information you provided in App Store Connect indicates you collect data in order to track the user, including Advertising Data, User ID, **Coarse Location,** Demographics (race, religion, etc.), Sensitive Info, Product Interaction, and Device ID. However, you do not use App Tracking Transparency to request the user's permission before tracking their activity.
Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them. This requirement protects the privacy of App Store users."_

I'm sure Firebase Analytics collects "Coarse Location", I can see it in my firebase console. I see a city where there is a user. So, apparently, I still have to use the ATT plugin :(

**Comment by yokochi** [comment]
@SnailRabbids I believe Firebase uses [IDFV](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) and not IDFA. Maybe, but I don't know the details so I can't say for sure. There is currently no option to turn off Analytics either.

**Comment by SnailRabbids** [comment]
@yokochi Can I ask you to update the plugin and add this simple feature? Your plugin is the only one that works well, of all that I found on github ... So looks like I cannot continue develop my application w/o this :(

I'm not sure I can ask you for that, but this is the only way for me to continue my work, I'm sorry :(

I mean just two simple methods as "startFirebaseAnalytics()" and "stopFirebaseAnalytics()" that calls "godot_firebase_analytics_init()" and "..._deinit()". At least just first one for "...init()".  I've never worked with plugins development for godot, I could be wrong.

**Comment by yokochi** [comment]
@SnailRabbids Added a method to explicitly initialize Firebase. Please check [here](https://github.com/funseek/godot-ios-firebase-analytics/tree/v1.0.0#how-to-use-it-with-gdscript)

**Comment by SnailRabbids** [comment]
@yokochi Thank you very much! I'll try it as soon as possible.

**Comment by SnailRabbids** [comment]
@yokochi Works for me, thank you!
Unfortunately there is another problem :(
https://github.com/funseek/godot-ios-att/issues/1
